### ISSUE TITLE
be independent of `go list -m -mod=readonly -json all`，Implement this feature in the source code

### ISSUE THREAD

**Issue by fly-studio** [visualfc/gomod#1]
When I have running a complex project with [igop](https://github.com/fly-studio/igop), I don't want to ship a `Golang` executor in the OS

Project structure
```
- main.go
- go.mod
- go.sum  <--- go list -m actually read this file to show modules
  - vendor/
     - github.com/..../.../
     - modules.txt
  - sub-module/
     - func.go
```

I saw the implementation code using a `go` executor  that to read modules
```
"go", "list", "-m", "-mod=readonly", "-json", "all"
```

But there is no `GO` executor in the operating system that `igop` on it, How do I do?

**Comment by visualfc** [comment]
https://github.com/goplus/igop/blob/main/context.go#L75
ctx.Lookup = nil // disable to use build.Import for lookup. support vendor and local pkg . (slow)
ctx.Lookup = func(root, path string) (dir string, found bool) { ... } // custom lookup mod path
ctx.AddImport(path string, dir string) // manual add import path from dir
